### PR TITLE
Release fixes

### LINKED ISSUE #206: Reorder Parameters in сategorical scales
Rearrange the parameters in the categorical function to the following order:
```kotlin
MappingParameters<DomainType, RangeType>.categorical(domain: List<DomainType>? = null, range: List<RangeType>? = null) ...
```

### LINKED ISSUE #216: Add a check if at least one layer has been added

### LINKED ISSUE #230: Bring the name of multiple geoms into one form
Now we have `bars`, `points`, but `tile` instead of `tiles`, `errorBar` instead of `errorBars` etc.

### PR DESCRIPTION
**Pull request by AndreiKingsley**
* close #206
* close #230 
* close #216

### CODE REVIEW

File: kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxplots.kt [hunk 1]
```diff
@@ -62,9 +62,9 @@ import org.jetbrains.kotlinx.kandy.letsplot.feature.position
  * ```
  */
 @Suppress("invisible_reference")
-public inline fun LayerCollectorContext.boxplot(block: BoxplotContext.() -> Unit) {
+public inline fun LayerCollectorContext.boxplots(block: BoxplotsContext.() -> Unit) {
```
Comment (devcrocod) [inline kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxplots.kt]: Can't there be one boxplot?

File: kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt [hunk 2]
```diff
@@ -40,7 +40,7 @@ import org.jetbrains.kotlinx.kandy.letsplot.feature.position
  * Example:
  *
  * ```
- * boxplots {
+ * boxes {
```
Comment (devcrocod) [inline kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt:43]: Is this a recognizable boxplot name?

File: kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/contexts.kt [hunk 3]
```diff
@@ -527,6 +527,9 @@ public abstract class LayerPlotContext : LayerCollectorContext(), PlotContext {
     override val bindingCollector: BindingCollector = BindingCollector()
 
     public override fun toPlot(): Plot {
+        if (layers.isEmpty()) {
```
Comment (devcrocod) [inline kandy-api/src/main/kotlin/org/jetbrains/kotlinx/kandy/dsl/internal/contexts.kt:530]: use check, it's more compact without if

**Review by devcrocod — CHANGES_REQUESTED** [review]
I have questions about plurals. You should call a layer plural if its typical use involves multiple objects, such as bars or points.
Also check that the renaming also affects the documentation: kdocs, readme, notebooks.

File: kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt (hunk 2 above)
Comment (AndreiKingsley) [reply kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/boxes.kt:43]: Boxplot is a statistical plot [wiki definition](https://en.wikipedia.org/wiki/Box_plot).
Box (with whiskers) is a geom: it can be used not only for a boxplot but also for example candlestick plot

**Review by devcrocod — APPROVED** [review]
