### PR TITLE
Testing kandy lets plot

### LINKED ISSUE #185: Test saving plots as images in `kandy-lets-plot`

### LINKED ISSUE #186: Test facet plots in `kandy-lets-plot`

### LINKED ISSUE #187: Test coordFlip feature in `kandy-lets-plot`

### LINKED ISSUE #188: Test reversed feature in kandy-lets-plot

### LINKED ISSUE #189: Test settings layout feature in `kandy-lets-plot`

### LINKED ISSUE #190: Test layers in `kandy-lets-plot`

### LINKED ISSUE #223: Type not checked
## **To Reproduce**
```kotlin
    val slope by columnOf(2) named "slope"
    val inter by columnOf(0.2) named "inter"
    val df = dataFrameOf(slope, inter)
    df.plot {
        abLine {
            slope(slope)
            intercept<Short>("inter")
        }
    }.save("test.png")
```

## **Screenshots**
test

### PR DESCRIPTION
**Pull request by devcrocod**
* close #185
* close #186 
* close #187 
* close #188 
* close #189 
* close #190 
* close #223

### CODE REVIEW

File: kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/context/PathContext.kt [hunk 1]
```diff
@@ -9,7 +9,7 @@ import org.jetbrains.kotlinx.kandy.dsl.internal.LayerContext
 import org.jetbrains.kotlinx.kandy.ir.geom.Geom
 import org.jetbrains.kotlinx.kandy.letsplot.layers.geom.PATH
 
-public open class PathContext(parent: LayerCollectorContext) : LayerContext(parent), LineInterface {
```
Comment (AndreiKingsley) [inline kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/layers/context/PathContext.kt:12]: All layer classes should be open to allow modification by third-party

File: kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/multiplot/facet/facet.kt
Comment (AndreiKingsley) [inline kandy-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/kandy/letsplot/multiplot/facet/facet.kt:1]: Remove direct companion properties imports

**Review by AndreiKingsley — CHANGES_REQUESTED** [review]
small changes

**Review by AndreiKingsley — APPROVED** [review]
